### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BlueBeard63** [papershredder432/PSRMPoliceUtilities#3]
Just a suggestion but why dont you add it so that the police officer can fine and check the fines by doing /history or some other command. It could also show if the player was jailed and for what reason.

**Comment by papershredder432** [comment]
A history command would take up too much space, as in for `.json` files, and I'd rather not dabble into MySQL.
`Fine` isn't a command yet, but can be implemented if you would explain the best way to do so.
And currently, `isjailed` should show if a player is jailed, for what reason, and the expire time (or was it the length?).

**Comment by BlueBeard63** [comment]
You could store it in a LiteDB database as it would mean that it would still stay accessible to people who dont use MySQL

**Comment by papershredder432** [comment]
> You could store it in a LiteDB database as it would mean that it would still stay accessible to people who dont use MySQL

I've barely touched MySQL as is, but going to something I've never even touched would be more difficult.
But I do know someone that does, I might be able to pull them in.

[<@492385120771375114>]

**Comment by Charterino** [comment]
What are you using at the moment? Are fines synchronized across servers?

**Comment by BlueBeard63** [comment]
> > You could store it in a LiteDB database as it would mean that it would still stay accessible to people who dont use MySQL
> 
> I've barely touched MySQL as is, but going to something I've never even touched would be more difficult.
> But I do know someone that does, I might be able to pull them in.
> 
> [<@492385120771375114>]

You could ask Feli as he likes to use it and knows a lot about it.

**Comment by papershredder432** [comment]
> > > You could store it in a LiteDB database as it would mean that it would still stay accessible to people who dont use MySQL
> > 
> > 
> > I've barely touched MySQL as is, but going to something I've never even touched would be more difficult.
> > But I do know someone that does, I might be able to pull them in.
> > [<@492385120771375114>]
> 
> You could ask Feli as he likes to use it and knows a lot about it.

Already got the person I was talking about, and I don't really know Feli much.

I got [Charterino](https://github.com/Charterino) instead.

**Comment by Charterino** [comment]
Why am I referred to as I'm a pokemon? Thanks for casting me.

**Comment by BlueBeard63** [comment]
You own him ?

**Comment by papershredder432** [comment]
> You own him ?

[REDACTED]

**Comment by Charterino** [comment]
He does own me. He also only feeds me once a day. Please send help. I'm locked in his basement. The PC I'm forced to work on is 15 years old. It's a nightmare. Please. I beg you. Send help.

**Comment by BlueBeard63** [comment]
Whats the address ? Hold on im getting help lol

**Comment by papershredder432** [comment]
Closing because we should be solving Fine history with LiteDB, as well as being implemented.

*shit*
